/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/map/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Config */
        get: operations["map_config_api_v1_map_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Topology */
        get: operations["workflow_topology_api_v1_workflow_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_v1_runs__thread_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/checkpoints/{checkpoint_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint State */
        get: operations["get_checkpoint_state_api_v1_runs__thread_id__checkpoints__checkpoint_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/checkpoints/{checkpoint_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Evidence */
        get: operations["get_checkpoint_evidence_api_v1_runs__thread_id__checkpoints__checkpoint_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/checkpoints/{checkpoint_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Plan */
        get: operations["get_checkpoint_plan_api_v1_runs__thread_id__checkpoints__checkpoint_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/checkpoints/{checkpoint_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Map */
        get: operations["get_checkpoint_map_api_v1_runs__thread_id__checkpoints__checkpoint_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/checkpoints/{checkpoint_id}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Routes */
        get: operations["get_checkpoint_routes_api_v1_runs__thread_id__checkpoints__checkpoint_id__routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/checkpoints/{checkpoint_id}/route-geometry/{route_geometry_reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Route Geometry */
        get: operations["get_checkpoint_route_geometry_api_v1_runs__thread_id__checkpoints__checkpoint_id__route_geometry__route_geometry_reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_v1_runs__thread_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay Run */
        post: operations["replay_run_api_v1_runs__thread_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fork Run */
        post: operations["fork_run_api_v1_runs__thread_id__fork_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{thread_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Runs */
        get: operations["compare_runs_api_v1_runs__thread_id__compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_api_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation Events */
        get: operations["get_operation_events_api_v1_operations__operation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionableTradeoffDecision */
        ActionableTradeoffDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "actionable_tradeoff";
            /**
             * Option
             * @enum {string}
             */
            option: "expand_search_radius" | "widen_seasonal_window" | "consider_related_taxa" | "keep_constraints_accept_low_confidence" | "accept_context_only" | "continue_with_weather_acknowledgement" | "accept_uncertain_access" | "revise_rain_preference";
            /** Search Radius Km */
            search_radius_km?: number | null;
            /** Seasonal Window Radius Months */
            seasonal_window_radius_months?: number | null;
        };
        /** BirdCorrectionDecision */
        BirdCorrectionDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "bird_input_correction";
            /** Bird Input */
            bird_input: string;
        };
        /** CheckpointSummary */
        CheckpointSummary: {
            /** Thread Id */
            thread_id: string;
            /** Branch Id */
            branch_id: string;
            /** Execution Id */
            execution_id: string;
            /** Parent Execution Id */
            parent_execution_id?: string | null;
            /** Replayed From Checkpoint Id */
            replayed_from_checkpoint_id?: string | null;
            /** Parent Branch Id */
            parent_branch_id?: string | null;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Parent Checkpoint Id */
            parent_checkpoint_id?: string | null;
            /** Forked From Checkpoint Id */
            forked_from_checkpoint_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Node Id */
            node_id: string;
            /** Graph Step */
            graph_step?: number | null;
            /** Source */
            source?: string | null;
            /** Next Nodes */
            next_nodes?: string[];
            /** Interrupt Kind */
            interrupt_kind?: string | null;
            /** Terminal Status */
            terminal_status?: string | null;
            /** Applied Constraint Changes */
            applied_constraint_changes?: {
                [key: string]: unknown;
            }[];
            /** Final Checkpoint Id */
            final_checkpoint_id?: string | null;
        };
        /** ComparedValue */
        ComparedValue: {
            /** Checkpoint A */
            checkpoint_a?: unknown;
            /** Checkpoint B */
            checkpoint_b?: unknown;
            /** Changed */
            changed: boolean;
        };
        /** ComparisonView */
        ComparisonView: {
            comparison: components["schemas"]["PlanComparison"];
        };
        /** ConstraintView */
        ConstraintView: {
            /** Code */
            code: string;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Request */
            request: string;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Data Mode
             * @default fixture
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /**
             * Model Mode
             * @default scripted
             * @enum {string}
             */
            model_mode: "scripted" | "live";
        };
        /** ElevationSampleView */
        ElevationSampleView: {
            /** Distance M */
            distance_m: number;
            /** Elevation M */
            elevation_m: number;
        };
        /** EvidenceCountsView */
        EvidenceCountsView: {
            /**
             * Server Match Count
             * @default 0
             */
            server_match_count: number;
            /**
             * Sampled Count
             * @default 0
             */
            sampled_count: number;
            /**
             * Deduplicated Count
             * @default 0
             */
            deduplicated_count: number;
            /**
             * Exact Duplicates Removed
             * @default 0
             */
            exact_duplicates_removed: number;
            /**
             * Possible Duplicates Retained
             * @default 0
             */
            possible_duplicates_retained: number;
            /**
             * Retained Count
             * @default 0
             */
            retained_count: number;
            /**
             * Rejected Count
             * @default 0
             */
            rejected_count: number;
            /**
             * Ranking Eligible Count
             * @default 0
             */
            ranking_eligible_count: number;
        };
        /** EvidenceGateCriterionView */
        EvidenceGateCriterionView: {
            /**
             * Key
             * @enum {string}
             */
            key: "ranking_eligible_records" | "spatial_cells_1km" | "ranking_datasets";
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Minimum */
            minimum: number;
            /** Passed */
            passed: boolean;
        };
        /** EvidenceGateView */
        EvidenceGateView: {
            /** Passed */
            passed: boolean;
            /** Criteria */
            criteria: components["schemas"]["EvidenceGateCriterionView"][];
        };
        /** EvidenceQualityView */
        EvidenceQualityView: {
            /**
             * Spatial Cell Count
             * @default 0
             */
            spatial_cell_count: number;
            /**
             * Safe Map Cell Count
             * @default 0
             */
            safe_map_cell_count: number;
            /**
             * Retained Dataset Count
             * @default 0
             */
            retained_dataset_count: number;
            /**
             * Ranking Dataset Count
             * @default 0
             */
            ranking_dataset_count: number;
            /**
             * Dominant Ranking Dataset Share
             * @default 0
             */
            dominant_ranking_dataset_share: number;
            /**
             * Dominant Basis Of Record Share
             * @default 0
             */
            dominant_basis_of_record_share: number;
            /** Quality Percentages */
            quality_percentages?: {
                [key: string]: number;
            };
            /** Year Distribution */
            year_distribution?: {
                [key: string]: number;
            };
            /** Month Distribution */
            month_distribution?: {
                [key: string]: number;
            };
            /** Warnings */
            warnings?: string[];
        };
        /** EvidenceView */
        EvidenceView: {
            /** Thread Id */
            thread_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Branch Id */
            branch_id: string;
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "strong" | "limited" | "insufficient" | "source_failure";
            /** Occurrence Outcome */
            occurrence_outcome?: string | null;
            /** Reason */
            reason?: string | null;
            counts: components["schemas"]["EvidenceCountsView"];
            quality: components["schemas"]["EvidenceQualityView"];
            gate: components["schemas"]["EvidenceGateView"];
            /** Seasonal Target Month */
            seasonal_target_month?: number | null;
            /** Seasonal Months */
            seasonal_months?: number[];
            /** Year Window */
            year_window?: [
                number,
                number
            ] | null;
            /** Candidate Sites */
            candidate_sites?: components["schemas"]["PlanSiteView"][];
            /** Contextual Sites */
            contextual_sites?: components["schemas"]["PlanSiteView"][];
            /** Constraints */
            constraints?: components["schemas"]["ConstraintView"][];
            weather?: components["schemas"]["WeatherDayView"] | null;
            /** Provenance */
            provenance?: components["schemas"]["ProvenanceView"][];
            /** Limitations */
            limitations?: string[];
            /** Suggested Actions */
            suggested_actions?: string[];
            /**
             * Server Match Note
             * @default Server match count is not abundance or a population estimate.
             * @constant
             */
            server_match_note: "Server match count is not abundance or a population estimate.";
        };
        /** FinalPlanView */
        FinalPlanView: {
            /** Status */
            status: string;
            /** Target Species */
            target_species: string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Duration Hours */
            duration_hours: number;
            /** Resolved London Start Context */
            resolved_london_start_context: string;
            /** Recommended Sites */
            recommended_sites?: components["schemas"]["PlanSiteView"][];
            /** Contextual Sites */
            contextual_sites?: components["schemas"]["PlanSiteView"][];
            weather_context?: components["schemas"]["WeatherDayView"] | null;
            /** Constraints */
            constraints?: components["schemas"]["ConstraintView"][];
            /** Unresolved Limitations */
            unresolved_limitations?: string[];
            /** Suggested Next Actions */
            suggested_next_actions?: string[];
            /** Provenance References */
            provenance_references?: string[];
            /** Evidence Attributions */
            evidence_attributions?: string[];
            /** Evidence Citations */
            evidence_citations?: string[];
            /** Evidence Gate Passed */
            evidence_gate_passed: boolean;
            /**
             * Low Confidence Accepted
             * @default false
             */
            low_confidence_accepted: boolean;
            /** Low Confidence Notice */
            low_confidence_notice?: string | null;
            walking_plan?: components["schemas"]["ValidatedWalkingPlanView"] | null;
            /** Itinerary Summary */
            itinerary_summary?: string | null;
            /** Explanation */
            explanation: string;
            /** Generated By */
            generated_by: string;
        };
        /** ForkRunRequest */
        ForkRunRequest: {
            /** Checkpoint Id */
            checkpoint_id: string;
            updates: components["schemas"]["ForkUpdates"];
            /** Branch Label */
            branch_label?: string | null;
        };
        /** ForkUpdates */
        ForkUpdates: {
            /** Search Radius Km */
            search_radius_km?: number | null;
            /** Seasonal Window Radius Months */
            seasonal_window_radius_months?: number | null;
            /** Target Month Override */
            target_month_override?: number | null;
            /** Target Local Date */
            target_local_date?: string | null;
            rain_preference?: components["schemas"]["RainPreference"] | null;
            /** Duration Hours */
            duration_hours?: number | null;
            /** Maximum Walking Distance Km */
            maximum_walking_distance_km?: number | null;
            /** Selected Related Taxon Key */
            selected_related_taxon_key?: number | null;
        };
        /** GeoJSONGeometry */
        GeoJSONGeometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "Point" | "Polygon" | "MultiPolygon";
            /** Coordinates */
            coordinates: unknown;
        };
        /**
         * GeocodedLocationCandidateView
         * @description Coordinate-free location candidate safe for a typed HITL card.
         */
        GeocodedLocationCandidateView: {
            /** Candidate Id */
            candidate_id: string;
            /** Label */
            label: string;
            /** Locality */
            locality?: string | null;
            /** Administrative District */
            administrative_district?: string | null;
            /** Postcode */
            postcode?: string | null;
            /** Category */
            category?: string | null;
            /** Place Type */
            place_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Product
             * @default London Biodiversity Expedition Planner
             * @constant
             */
            product: "London Biodiversity Expedition Planner";
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /** Workflow Version */
            workflow_version: string;
            /**
             * Default Data Mode
             * @enum {string}
             */
            default_data_mode: "fixture" | "live";
            /**
             * Default Model Mode
             * @enum {string}
             */
            default_model_mode: "scripted" | "live";
            /** Allowed Run Modes */
            allowed_run_modes: components["schemas"]["RunModeView"][];
            /** Public Demo */
            public_demo: boolean;
        };
        /** HistoryView */
        HistoryView: {
            /** Checkpoints */
            checkpoints: components["schemas"]["CheckpointSummary"][];
            /** Branches */
            branches: components["schemas"]["RunBranch"][];
            /** Executions */
            executions: components["schemas"]["RunExecution"][];
        };
        /** HitlOptionView */
        HitlOptionView: {
            /** Option */
            option: string;
            /** Current Radius Km */
            current_radius_km?: number | null;
            /** Maximum Radius Km */
            maximum_radius_km?: number | null;
            /** Current Radius Months */
            current_radius_months?: number | null;
            /** Maximum Radius Months */
            maximum_radius_months?: number | null;
            /** Candidate Count */
            candidate_count?: number | null;
            /** Relation Levels */
            relation_levels?: string[];
            /** Current Seasonal Months */
            current_seasonal_months?: number[];
            /** Next Seasonal Months */
            next_seasonal_months?: number[];
            /** Year Window */
            year_window?: [
                number,
                number
            ] | null;
            /** Current Server Match Count */
            current_server_match_count?: number | null;
            /** Current Ranking Eligible Count */
            current_ranking_eligible_count?: number | null;
            /** Minimum Walking Distance Km */
            minimum_walking_distance_km?: number | null;
        };
        /** JourneySegmentView */
        JourneySegmentView: {
            /** Segment Id */
            segment_id: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "outbound" | "return";
            /** Sequence */
            sequence: number;
            /** Mode */
            mode: string;
            /** Line Name */
            line_name?: string | null;
            /** Instruction */
            instruction: string;
            /** Origin Label */
            origin_label?: string | null;
            /** Destination Label */
            destination_label?: string | null;
            /** Duration Minutes */
            duration_minutes: number;
            /** Distance M */
            distance_m?: number | null;
            /** Departure Time */
            departure_time?: string | null;
            /** Arrival Time */
            arrival_time?: string | null;
        };
        /** LocationCorrectionDecision */
        LocationCorrectionDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "location_correction";
            /** Postcode */
            postcode?: string | null;
            /** Candidate Id */
            candidate_id?: string | null;
        };
        /** MapCellFeature */
        MapCellFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["GeoJSONGeometry"];
            properties: components["schemas"]["MapCellProperties"];
        };
        /** MapCellProperties */
        MapCellProperties: {
            /** Display Id */
            display_id: string;
            /**
             * Layer
             * @default aggregate_evidence
             * @constant
             */
            layer: "aggregate_evidence";
            /**
             * Density Band
             * @enum {string}
             */
            density_band: "lower" | "medium" | "higher";
            /**
             * Dataset Diversity Band
             * @enum {string}
             */
            dataset_diversity_band: "single" | "multiple";
            /** Date Start */
            date_start?: string | null;
            /** Date End */
            date_end?: string | null;
            /** Label */
            label: string;
        };
        /** MapConfigView */
        MapConfigView: {
            /** Style Url */
            style_url?: string | null;
            /** Provider */
            provider: string;
            /** Attributions */
            attributions: string[];
            /**
             * Fallback Message
             * @default Basemap unavailable — evidence overlays remain available
             * @constant
             */
            fallback_message: "Basemap unavailable — evidence overlays remain available";
        };
        /** MapEvidenceView */
        MapEvidenceView: {
            /** Thread Id */
            thread_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Branch Id */
            branch_id: string;
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "strong" | "limited" | "insufficient" | "source_failure";
            /** Aggregate Grid */
            aggregate_grid?: components["schemas"]["MapCellFeature"][];
            /** Candidate Sites */
            candidate_sites?: components["schemas"]["MapSiteFeature"][];
            /** Contextual Sites */
            contextual_sites?: components["schemas"]["MapSiteFeature"][];
            start_context?: components["schemas"]["MapStartContext"] | null;
            selected_entrance?: components["schemas"]["MapStartContext"] | null;
            /** Selected Site Id */
            selected_site_id?: string | null;
            /** Route Status */
            route_status?: string | null;
            /** Route Geometry Reference */
            route_geometry_reference?: string | null;
            /** Attributions */
            attributions: string[];
            /** Limitations */
            limitations: string[];
            /** Grid Note */
            grid_note: string;
        };
        /** MapSiteFeature */
        MapSiteFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["GeoJSONGeometry"];
            properties: components["schemas"]["MapSiteProperties"];
        };
        /** MapSiteProperties */
        MapSiteProperties: {
            /** Site Id */
            site_id: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "candidate" | "contextual";
            /** Name */
            name: string;
            /** Site Type */
            site_type: string;
            /** Access Certainty */
            access_certainty: string;
            /** Evidence Tier */
            evidence_tier: string;
            /** Approximate Straight Line Distance Km */
            approximate_straight_line_distance_km: number;
            /** Operator */
            operator?: string | null;
            /** Opening Hours */
            opening_hours?: string | null;
            /** Website */
            website?: string | null;
        };
        /** MapStartContext */
        MapStartContext: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["GeoJSONGeometry"];
            /** Properties */
            properties: {
                [key: string]: string;
            };
        };
        /** OperationAccepted */
        OperationAccepted: {
            /** Operation Id */
            operation_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
            /** Events Url */
            events_url: string;
        };
        /** OperationView */
        OperationView: {
            /** Operation Id */
            operation_id: string;
            /** Thread Id */
            thread_id: string;
            /** Branch Id */
            branch_id?: string | null;
            /** Execution Id */
            execution_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "start" | "resume" | "replay" | "fork";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_for_input" | "completed" | "failed";
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /**
             * Model Mode
             * @enum {string}
             */
            model_mode: "scripted" | "live";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Last Event Sequence
             * @default 0
             */
            last_event_sequence: number;
            /** Current Checkpoint Id */
            current_checkpoint_id?: string | null;
            /** Interrupt Kind */
            interrupt_kind?: string | null;
            /** Error Code */
            error_code?: string | null;
        };
        /**
         * ParsedRequestDraftView
         * @description Safe, editable request fields already extracted before clarification.
         */
        ParsedRequestDraftView: {
            /** Bird Input */
            bird_input?: string | null;
            /** Postcode */
            postcode?: string | null;
            /** Location Query */
            location_query?: string | null;
            /**
             * Has Explicit Start Point
             * @default false
             */
            has_explicit_start_point: boolean;
            /** Target Local Date */
            target_local_date?: string | null;
            /** Duration Hours */
            duration_hours?: number | null;
        };
        /** PendingDecisionView */
        PendingDecisionView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "request_clarification" | "location_correction" | "bird_input_correction" | "taxon_selection" | "actionable_tradeoff" | "related_taxon_selection" | "route_tradeoff";
            /** Question */
            question: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Branch Id */
            branch_id: string;
            /** Execution Id */
            execution_id: string;
            /** Validation Errors */
            validation_errors?: string[];
            /** Status */
            status?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Candidates */
            candidates?: components["schemas"]["TaxonCandidateView"][];
            /** Location Candidates */
            location_candidates?: components["schemas"]["GeocodedLocationCandidateView"][];
            /** Options */
            options?: components["schemas"]["HitlOptionView"][];
            parsed_draft?: components["schemas"]["ParsedRequestDraftView"] | null;
        };
        /** PlanComparison */
        PlanComparison: {
            /** Thread Id */
            thread_id: string;
            /** Checkpoint A */
            checkpoint_a: string;
            /** Checkpoint B */
            checkpoint_b: string;
            request_constraints: components["schemas"]["ComparedValue"];
            selected_taxon: components["schemas"]["ComparedValue"];
            evidence_outcome: components["schemas"]["ComparedValue"];
            weather_status: components["schemas"]["ComparedValue"];
            plan_status: components["schemas"]["ComparedValue"];
            recommended_site_ids: components["schemas"]["ComparedValue"];
            contextual_site_ids: components["schemas"]["ComparedValue"];
            limitations: components["schemas"]["ComparedValue"];
            provenance_sources: components["schemas"]["ComparedValue"];
            applied_user_decisions: components["schemas"]["ComparedValue"];
            route_status: components["schemas"]["ComparedValue"];
            selected_route_site_id: components["schemas"]["ComparedValue"];
            total_walking_distance_km: components["schemas"]["ComparedValue"];
            remaining_field_time_minutes: components["schemas"]["ComparedValue"];
            route_constraints: components["schemas"]["ComparedValue"];
            /** Changed Fields */
            changed_fields?: ("request_constraints" | "selected_taxon" | "evidence_outcome" | "weather_status" | "plan_status" | "recommended_site_ids" | "contextual_site_ids" | "limitations" | "provenance_sources" | "applied_user_decisions" | "route_status" | "selected_route_site_id" | "total_walking_distance_km" | "remaining_field_time_minutes" | "route_constraints")[];
        };
        /** PlanSiteView */
        PlanSiteView: {
            /** Site Id */
            site_id: string;
            /** Name */
            name: string;
            /** Access Certainty */
            access_certainty: string;
            /** Approximate Straight Line Distance Km */
            approximate_straight_line_distance_km: number;
            /** Evidence Tier */
            evidence_tier: string;
        };
        /** ProvenanceView */
        ProvenanceView: {
            /** Source */
            source: string;
            /** Source Record Type */
            source_record_type: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Licence */
            licence: string;
            /** Attribution */
            attribution: string;
            /** Use Classification */
            use_classification: string;
            /** Source Reference */
            source_reference?: string | null;
            /** Limitations */
            limitations?: string[];
        };
        /** PublicEntranceView */
        PublicEntranceView: {
            /** Entrance Id */
            entrance_id: string;
            /** Site Id */
            site_id: string;
            /** Label */
            label: string;
            /**
             * Access Certainty
             * @enum {string}
             */
            access_certainty: "explicit_public" | "unspecified";
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
            /** Wheelchair */
            wheelchair?: string | null;
            /** Opening Hours */
            opening_hours?: string | null;
            /**
             * Association Method
             * @constant
             */
            association_method: "osm_boundary_member";
            /** Limitations */
            limitations?: string[];
        };
        /**
         * RainPreference
         * @enum {string}
         */
        RainPreference: "no_preference" | "avoid_heavy_rain";
        /** ReplayRunRequest */
        ReplayRunRequest: {
            /** Checkpoint Id */
            checkpoint_id: string;
        };
        /** RequestClarificationDecision */
        RequestClarificationDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "request_clarification";
            /** Updates */
            updates: {
                [key: string]: unknown;
            };
        };
        /** ResumeRunRequest */
        ResumeRunRequest: {
            /** Decision */
            decision: components["schemas"]["TaxonSelectionDecision"] | components["schemas"]["BirdCorrectionDecision"] | components["schemas"]["LocationCorrectionDecision"] | components["schemas"]["RequestClarificationDecision"] | components["schemas"]["ActionableTradeoffDecision"] | components["schemas"]["RouteTradeoffDecision"];
            /** Checkpoint Id */
            checkpoint_id?: string | null;
            /** Branch Id */
            branch_id?: string | null;
        };
        /** RouteConstraintView */
        RouteConstraintView: {
            /** Code */
            code: string;
            /** Passed */
            passed: boolean;
            /** Actual Value */
            actual_value?: number | null;
            /** Limit Value */
            limit_value?: number | null;
            /** Unit */
            unit?: string | null;
            /** Message */
            message: string;
        };
        /** RouteGeometryView */
        RouteGeometryView: {
            /** Thread Id */
            thread_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Route Geometry Reference */
            route_geometry_reference: string;
            /**
             * Origin Visibility
             * @enum {string}
             */
            origin_visibility: "local_private" | "planned_public_fixture";
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
            /** Limitations */
            limitations?: string[];
        };
        /** RouteOptionView */
        RouteOptionView: {
            /** Option Id */
            option_id: string;
            /** Status */
            status: string;
            /** Site Id */
            site_id: string;
            /** Site Name */
            site_name: string;
            entrance: components["schemas"]["PublicEntranceView"];
            /** Outbound Distance Km */
            outbound_distance_km?: number | null;
            /** Return Distance Km */
            return_distance_km?: number | null;
            /** Total Distance Km */
            total_distance_km?: number | null;
            /** Walking Duration Minutes */
            walking_duration_minutes?: number | null;
            /** Total Travel Duration Minutes */
            total_travel_duration_minutes?: number | null;
            /** Feasible */
            feasible: boolean;
            /** Provider */
            provider?: string | null;
            /** Cache Status */
            cache_status?: string | null;
            /** Route Geometry Reference */
            route_geometry_reference?: string | null;
            /** Constraint Results */
            constraint_results?: components["schemas"]["RouteConstraintView"][];
            /** Warnings */
            warnings?: string[];
        };
        /** RouteOptionsView */
        RouteOptionsView: {
            /** Thread Id */
            thread_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Branch Id */
            branch_id: string;
            /** Execution Id */
            execution_id: string;
            /** Status */
            status: string;
            /** Selected Option Id */
            selected_option_id?: string | null;
            /** Options */
            options?: components["schemas"]["RouteOptionView"][];
            /** Provider Status */
            provider_status: string;
            /** Limitations */
            limitations?: string[];
        };
        /** RouteTradeoffDecision */
        RouteTradeoffDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "route_tradeoff";
            /**
             * Option
             * @enum {string}
             */
            option: "accept_uncertain_entrance" | "increase_maximum_walking_distance" | "keep_route_constraints_and_end";
            /** Maximum Walking Distance Km */
            maximum_walking_distance_km?: number | null;
        };
        /** RunBranch */
        RunBranch: {
            /** Thread Id */
            thread_id: string;
            /** Branch Id */
            branch_id: string;
            /** Parent Branch Id */
            parent_branch_id?: string | null;
            /** Head Checkpoint Id */
            head_checkpoint_id: string;
            /** Final Checkpoint Id */
            final_checkpoint_id?: string | null;
            /** Forked From Checkpoint Id */
            forked_from_checkpoint_id?: string | null;
            /** Fork Updates */
            fork_updates?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Terminal Status */
            terminal_status?: string | null;
        };
        /** RunDetail */
        RunDetail: {
            run: components["schemas"]["RunSummary"];
            submitted_request?: components["schemas"]["SubmittedRequestView"] | null;
            /** Operations */
            operations?: components["schemas"]["OperationView"][];
            /** Branches */
            branches?: components["schemas"]["RunBranch"][];
            /** Executions */
            executions?: components["schemas"]["RunExecution"][];
            /** Pending Decisions */
            pending_decisions?: components["schemas"]["PendingDecisionView"][];
            final_plan?: components["schemas"]["FinalPlanView"] | null;
        };
        /** RunExecution */
        RunExecution: {
            /** Thread Id */
            thread_id: string;
            /** Execution Id */
            execution_id: string;
            /** Branch Id */
            branch_id: string;
            /** Parent Execution Id */
            parent_execution_id?: string | null;
            /** Replayed From Checkpoint Id */
            replayed_from_checkpoint_id?: string | null;
            /** Head Checkpoint Id */
            head_checkpoint_id: string;
            /** Final Checkpoint Id */
            final_checkpoint_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Terminal Status */
            terminal_status?: string | null;
            /** Interrupt Kind */
            interrupt_kind?: string | null;
        };
        /** RunModeView */
        RunModeView: {
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /**
             * Model Mode
             * @enum {string}
             */
            model_mode: "scripted" | "live";
        };
        /** RunSummary */
        RunSummary: {
            /** Thread Id */
            thread_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_for_input" | "completed" | "failed";
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "live";
            /**
             * Model Mode
             * @enum {string}
             */
            model_mode: "scripted" | "live";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Current Checkpoint Id */
            current_checkpoint_id?: string | null;
            /** Branch Id */
            branch_id?: string | null;
            /** Execution Id */
            execution_id?: string | null;
            /** Interrupt Kind */
            interrupt_kind?: string | null;
        };
        /** StateCountersView */
        StateCountersView: {
            /**
             * Evidence Loop Count
             * @default 0
             */
            evidence_loop_count: number;
            /**
             * Plan Revision Count
             * @default 0
             */
            plan_revision_count: number;
            /**
             * Recorded Tool Call Count
             * @default 0
             */
            recorded_tool_call_count: number;
        };
        /** StateDecisionView */
        StateDecisionView: {
            /** Kind */
            kind: string;
            /** Option */
            option?: string | null;
            /** Accepted Taxon Key */
            accepted_taxon_key?: number | null;
            /** Selected Taxon Name */
            selected_taxon_name?: string | null;
            /** Bird Input */
            bird_input?: string | null;
            /** Relation Level */
            relation_level?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Search Radius Km */
            search_radius_km?: number | null;
            /** Seasonal Window Radius Months */
            seasonal_window_radius_months?: number | null;
            /** Maximum Walking Distance Km */
            maximum_walking_distance_km?: number | null;
            /** Changed Fields */
            changed_fields?: string[];
        };
        /** StateEvidenceView */
        StateEvidenceView: {
            /** Occurrence Outcome */
            occurrence_outcome?: string | null;
            /** Sampled Count */
            sampled_count?: number | null;
            /** Retained Count */
            retained_count?: number | null;
            /** Ranking Eligible Count */
            ranking_eligible_count?: number | null;
            /**
             * Safe Map Cell Count
             * @default 0
             */
            safe_map_cell_count: number;
            /** Weather Status */
            weather_status?: string | null;
            /** Public Site Status */
            public_site_status?: string | null;
            /**
             * Candidate Site Count
             * @default 0
             */
            candidate_site_count: number;
            /**
             * Contextual Site Count
             * @default 0
             */
            contextual_site_count: number;
            /**
             * Public Entrance Count
             * @default 0
             */
            public_entrance_count: number;
            /**
             * Route Option Count
             * @default 0
             */
            route_option_count: number;
            /**
             * Tool Error Count
             * @default 0
             */
            tool_error_count: number;
        };
        /** StateHitlView */
        StateHitlView: {
            /**
             * Waiting
             * @default false
             */
            waiting: boolean;
            /** Interrupt Kind */
            interrupt_kind?: string | null;
            /** Applied Decisions */
            applied_decisions?: components["schemas"]["StateDecisionView"][];
        };
        /** StateLocationView */
        StateLocationView: {
            /** Status */
            status?: string | null;
            /** Input Kind */
            input_kind?: string | null;
            /** Within Greater London */
            within_greater_london?: boolean | null;
            /** Administrative District */
            administrative_district?: string | null;
        };
        /** StatePlanView */
        StatePlanView: {
            /** Deterministic Status */
            deterministic_status?: string | null;
            /** Final Status */
            final_status?: string | null;
            /** Generated By */
            generated_by?: string | null;
            /**
             * Recommended Site Count
             * @default 0
             */
            recommended_site_count: number;
            /**
             * Contextual Site Count
             * @default 0
             */
            contextual_site_count: number;
            /** Evidence Gate Passed */
            evidence_gate_passed?: boolean | null;
            /**
             * Low Confidence Accepted
             * @default false
             */
            low_confidence_accepted: boolean;
            /**
             * Grounding Error Count
             * @default 0
             */
            grounding_error_count: number;
            /** Route Status */
            route_status?: string | null;
            /** Selected Route Site Id */
            selected_route_site_id?: string | null;
            /** Total Walking Distance Km */
            total_walking_distance_km?: number | null;
            /** Total Travel Duration Minutes */
            total_travel_duration_minutes?: number | null;
            /** Remaining Field Time Minutes */
            remaining_field_time_minutes?: number | null;
            /** Routing Provider */
            routing_provider?: string | null;
            /** Route Cache Status */
            route_cache_status?: string | null;
        };
        /**
         * StateRequestView
         * @description Location-redacted request constraints safe for a frontend timeline.
         */
        StateRequestView: {
            /** Target Local Date */
            target_local_date?: string | null;
            /** Duration Hours */
            duration_hours?: number | null;
            /** Maximum Walking Distance Km */
            maximum_walking_distance_km?: number | null;
            /** Rain Preference */
            rain_preference?: string | null;
            /** Target Month Override */
            target_month_override?: number | null;
            /** Seasonal Window Radius Months */
            seasonal_window_radius_months?: number | null;
            /** Search Radius Km */
            search_radius_km?: number | null;
        };
        /** StateTaxonView */
        StateTaxonView: {
            /** Status */
            status?: string | null;
            /** Accepted Taxon Key */
            accepted_taxon_key?: number | null;
            /** Common Name */
            common_name?: string | null;
            /** Scientific Name */
            scientific_name?: string | null;
            /** Canonical Name */
            canonical_name?: string | null;
            /** Rank */
            rank?: string | null;
            /** Taxonomic Status */
            taxonomic_status?: string | null;
        };
        /**
         * StateView
         * @description Strictly allow-listed, coordinate-free view of one saved checkpoint.
         */
        StateView: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Thread Id */
            thread_id: string;
            /** Branch Id */
            branch_id: string;
            /** Execution Id */
            execution_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Parent Checkpoint Id */
            parent_checkpoint_id?: string | null;
            /** Node Id */
            node_id: string;
            /** Graph Step */
            graph_step: number;
            /** Source */
            source?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Next Nodes */
            next_nodes?: string[];
            /** Terminal Status */
            terminal_status?: string | null;
            request?: components["schemas"]["StateRequestView"] | null;
            location?: components["schemas"]["StateLocationView"] | null;
            taxon?: components["schemas"]["StateTaxonView"] | null;
            evidence: components["schemas"]["StateEvidenceView"];
            plan: components["schemas"]["StatePlanView"];
            hitl: components["schemas"]["StateHitlView"];
            counters: components["schemas"]["StateCountersView"];
            /** Invalidated Evidence */
            invalidated_evidence?: string[];
        };
        /**
         * SubmittedRequestView
         * @description Local-only display copy read from the durable graph checkpoint.
         */
        SubmittedRequestView: {
            /** Text */
            text: string;
            /**
             * Language
             * @default English
             * @constant
             */
            language: "English";
            /**
             * Visibility
             * @default local_only
             * @constant
             */
            visibility: "local_only";
        };
        /** TaxonCandidateView */
        TaxonCandidateView: {
            /** Accepted Taxon Key */
            accepted_taxon_key: number;
            /** Common Name */
            common_name?: string | null;
            /** Scientific Name */
            scientific_name: string;
            /** Canonical Name */
            canonical_name: string;
            /** Rank */
            rank: string;
            /** Taxonomic Status */
            taxonomic_status: string;
            /** Class Name */
            class_name?: string | null;
            /** Order */
            order?: string | null;
            /** Family */
            family?: string | null;
            /** Genus */
            genus?: string | null;
            /** Resolution Method */
            resolution_method: string;
            /** Confidence */
            confidence?: number | null;
            /** Relation Level */
            relation_level?: string | null;
            /** Relation Basis */
            relation_basis?: string | null;
            evidence_preview?: components["schemas"]["TaxonEvidencePreviewView"] | null;
        };
        /** TaxonEvidencePreviewView */
        TaxonEvidencePreviewView: {
            /** Status */
            status: string;
            /** Evidence Outcome */
            evidence_outcome?: string | null;
            /** Sampled Count */
            sampled_count?: number | null;
            /** Retained Count */
            retained_count?: number | null;
            /** Ranking Eligible Count */
            ranking_eligible_count?: number | null;
            /** Dataset Count */
            dataset_count?: number | null;
            /** Target Months */
            target_months?: number[];
            /** Source Status */
            source_status: string;
            /** Limitations */
            limitations?: string[];
        };
        /** TaxonSelectionDecision */
        TaxonSelectionDecision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "related_taxon_selection" | "taxon_selection";
            /** Accepted Taxon Key */
            accepted_taxon_key: number;
        };
        /** ValidatedWalkingPlanView */
        ValidatedWalkingPlanView: {
            /** Status */
            status: string;
            /** Selected Site Id */
            selected_site_id?: string | null;
            /** Selected Site Name */
            selected_site_name?: string | null;
            entrance?: components["schemas"]["PublicEntranceView"] | null;
            /** Routing Profile */
            routing_profile: string;
            /**
             * Journey Type
             * @default walking_only
             * @enum {string}
             */
            journey_type: "walking_only" | "public_transport_and_walking";
            /** Planning Departure Time Local */
            planning_departure_time_local?: string | null;
            /** Outbound Distance Km */
            outbound_distance_km?: number | null;
            /** Return Distance Km */
            return_distance_km?: number | null;
            /** Total Distance Km */
            total_distance_km?: number | null;
            /** Walking Duration Minutes */
            walking_duration_minutes?: number | null;
            /** Outbound Travel Duration Minutes */
            outbound_travel_duration_minutes?: number | null;
            /** Return Travel Duration Minutes */
            return_travel_duration_minutes?: number | null;
            /** Total Travel Duration Minutes */
            total_travel_duration_minutes?: number | null;
            /** Public Transport Duration Minutes */
            public_transport_duration_minutes?: number | null;
            /** Journey Segments */
            journey_segments?: components["schemas"]["JourneySegmentView"][];
            /**
             * Return Route Same As Outbound
             * @default false
             */
            return_route_same_as_outbound: boolean;
            /** Selection Rationale */
            selection_rationale?: string | null;
            /** Expedition Duration Minutes */
            expedition_duration_minutes: number;
            /** Remaining Field Time Minutes */
            remaining_field_time_minutes?: number | null;
            /** Ascent M */
            ascent_m?: number | null;
            /** Descent M */
            descent_m?: number | null;
            /** Elevation Profile */
            elevation_profile?: components["schemas"]["ElevationSampleView"][];
            /** Route Geometry Reference */
            route_geometry_reference?: string | null;
            /** Provider */
            provider?: string | null;
            /** Provider Version */
            provider_version?: string | null;
            /** Retrieved At */
            retrieved_at?: string | null;
            /** Licence */
            licence?: string | null;
            /** Attribution */
            attribution?: string | null;
            /** Cache Status */
            cache_status?: string | null;
            /** Constraint Results */
            constraint_results?: components["schemas"]["RouteConstraintView"][];
            /** Alternative Feasible Routes */
            alternative_feasible_routes?: components["schemas"]["RouteOptionView"][];
            /** Warnings */
            warnings?: string[];
            /** Limitations */
            limitations?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherDayView */
        WeatherDayView: {
            /** Status */
            status: string;
            /**
             * Requested Date
             * Format: date
             */
            requested_date: string;
            /** Maximum Temperature C */
            maximum_temperature_c?: number | null;
            /** Minimum Temperature C */
            minimum_temperature_c?: number | null;
            /** Precipitation Probability Percent */
            precipitation_probability_percent?: number | null;
            /** Precipitation Amount Mm */
            precipitation_amount_mm?: number | null;
            /** Weather Code */
            weather_code?: number | null;
            /** Explanation */
            explanation: string;
        };
        /** WorkflowEdgeView */
        WorkflowEdgeView: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Conditional
             * @default false
             */
            conditional: boolean;
            /** Route Label */
            route_label?: string | null;
        };
        /** WorkflowNodeView */
        WorkflowNodeView: {
            /** Node Id */
            node_id: string;
            /** Label */
            label: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "entry" | "intake" | "location" | "taxonomy" | "evidence" | "validation" | "routing" | "planning" | "outcome";
            /**
             * Kind
             * @enum {string}
             */
            kind: "start" | "end" | "model" | "deterministic" | "tool" | "hitl" | "terminal";
            /** Summary */
            summary: string;
            /** Order */
            order: number;
        };
        /** WorkflowTopologyView */
        WorkflowTopologyView: {
            /** Workflow Version */
            workflow_version: string;
            /** Nodes */
            nodes: components["schemas"]["WorkflowNodeView"][];
            /** Edges */
            edges: components["schemas"]["WorkflowEdgeView"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    map_config_api_v1_map_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapConfigView"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    workflow_topology_api_v1_workflow_topology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTopologyView"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_runs__thread_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_state_api_v1_runs__thread_id__checkpoints__checkpoint_id__state_get: {
        parameters: {
            query: {
                node_id: string;
                graph_step: number;
            };
            header?: never;
            path: {
                thread_id: string;
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_evidence_api_v1_runs__thread_id__checkpoints__checkpoint_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_plan_api_v1_runs__thread_id__checkpoints__checkpoint_id__plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalPlanView"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_map_api_v1_runs__thread_id__checkpoints__checkpoint_id__map_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapEvidenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_routes_api_v1_runs__thread_id__checkpoints__checkpoint_id__routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteOptionsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_route_geometry_api_v1_runs__thread_id__checkpoints__checkpoint_id__route_geometry__route_geometry_reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                checkpoint_id: string;
                route_geometry_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteGeometryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_runs__thread_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_run_api_v1_runs__thread_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fork_run_api_v1_runs__thread_id__fork_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_v1_runs__thread_id__compare_get: {
        parameters: {
            query: {
                checkpoint_a: string;
                checkpoint_b: string;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_api_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_events_api_v1_operations__operation_id__events_get: {
        parameters: {
            query?: {
                after_sequence?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
