import type {
  EvidenceView,
  FinalPlanView,
  HistoryView,
  MapEvidenceView,
  PlanComparison,
  RouteGeometryView,
  RouteOptionsView,
  StateView,
  WorkflowTopologyView,
} from "../api/contracts";

export const evidenceFixture: EvidenceView = {
  thread_id: "thread-one",
  checkpoint_id: "checkpoint-final",
  branch_id: "branch-original",
  execution_id: "execution-original",
  status: "strong",
  occurrence_outcome: "strong_map_evidence",
  reason: "The bounded historical sample passes the deterministic gate.",
  counts: {
    server_match_count: 24804,
    sampled_count: 300,
    deduplicated_count: 296,
    exact_duplicates_removed: 4,
    possible_duplicates_retained: 19,
    retained_count: 280,
    rejected_count: 16,
    ranking_eligible_count: 227,
  },
  quality: {
    spatial_cell_count: 31,
    safe_map_cell_count: 12,
    retained_dataset_count: 8,
    ranking_dataset_count: 6,
    dominant_ranking_dataset_share: 0.42,
    dominant_basis_of_record_share: 0.66,
    quality_percentages: { ranking_eligible: 81.1 },
    year_distribution: { "2025": 42 },
    month_distribution: { "6": 86 },
    warnings: ["Sampling is bounded and not exhaustive."],
  },
  gate: {
    passed: true,
    criteria: [
      { key: "ranking_eligible_records", label: "Ranking-eligible records", value: 227, minimum: 50, passed: true },
      { key: "spatial_cells_1km", label: "Distinct ranking 1 km cells", value: 31, minimum: 5, passed: true },
      { key: "ranking_datasets", label: "Ranking datasets", value: 6, minimum: 2, passed: true },
    ],
  },
  seasonal_target_month: 6,
  seasonal_months: [5, 6, 7],
  year_window: [2021, 2026],
  candidate_sites: [
    {
      site_id: "osm-way-1",
      name: "Evidence Garden",
      access_certainty: "unspecified",
      approximate_straight_line_distance_km: 1.2,
      evidence_tier: "directly_grounded",
    },
  ],
  contextual_sites: [],
  constraints: [
    {
      code: "greater_london_scope",
      status: "satisfied",
      severity: "information",
      message: "Validated inside Greater London.",
    },
    {
      code: "walking_distance",
      status: "unresolved",
      severity: "warning",
      message: "Routing is not available.",
    },
  ],
  weather: {
    status: "available",
    requested_date: "2026-06-15",
    maximum_temperature_c: 22,
    minimum_temperature_c: 13,
    precipitation_probability_percent: 25,
    precipitation_amount_mm: 0.4,
    weather_code: 2,
    explanation: "Exact-date daily weather only.",
  },
  provenance: [
    {
      source: "GBIF Occurrence Search API",
      source_record_type: "bounded occurrence search",
      retrieved_at: "2026-09-02T00:00:00Z",
      licence: "Dataset-specific licences",
      attribution: "GBIF.org and contributing datasets",
      use_classification: "spatial_ranking",
      limitations: [],
    },
  ],
  limitations: ["Historical evidence does not guarantee a sighting."],
  suggested_actions: [],
  server_match_note: "Server match count is not abundance or a population estimate.",
};

export const planFixture: FinalPlanView = {
  status: "candidate_plan_ready",
  target_species: "Columba palumbus",
  target_date: "2026-06-15",
  duration_hours: 2,
  resolved_london_start_context: "Generalised start context in Wandsworth, within Greater London.",
  recommended_sites: evidenceFixture.candidate_sites,
  contextual_sites: [
    {
      site_id: "osm-way-2",
      name: "Context Meadow",
      access_certainty: "unspecified",
      approximate_straight_line_distance_km: 1.8,
      evidence_tier: "ungrounded",
    },
  ],
  weather_context: evidenceFixture.weather,
  constraints: evidenceFixture.constraints,
  unresolved_limitations: [
    "Historical occurrence records do not predict or guarantee a sighting.",
    "Straight-line distance is not a walking route.",
  ],
  suggested_next_actions: [],
  provenance_references: ["https://www.gbif.org/developer/occurrence"],
  evidence_attributions: ["GBIF.org", "© OpenStreetMap contributors", "Open-Meteo"],
  evidence_citations: ["location", "taxonomy", "occurrence"],
  evidence_gate_passed: true,
  low_confidence_accepted: false,
  explanation: "A deterministic evidence-grounded candidate plan.",
  generated_by: "llm_composer",
};

export const walkingPlanFixture: NonNullable<FinalPlanView["walking_plan"]> = {
  status: "ready",
  selected_site_id: "osm-way-1",
  selected_site_name: "Evidence Garden",
  entrance: {
    entrance_id: "osm-node-101",
    site_id: "osm-way-1",
    label: "Main gate",
    access_certainty: "explicit_public",
    longitude: -0.1519,
    latitude: 51.5076,
    wheelchair: "yes",
    opening_hours: null,
    association_method: "osm_boundary_member",
    limitations: [],
  },
  routing_profile: "foot-walking",
  outbound_distance_km: 4.56,
  return_distance_km: 4.57,
  total_distance_km: 9.13,
  walking_duration_minutes: 121.8,
  expedition_duration_minutes: 180,
  remaining_field_time_minutes: 58.2,
  ascent_m: 31,
  descent_m: 30,
  elevation_profile: [
    { distance_m: 0, elevation_m: 7 },
    { distance_m: 4565, elevation_m: 20 },
    { distance_m: 9130, elevation_m: 7 },
  ],
  route_geometry_reference: "route-aaaaaaaaaaaaaaaaaaaaaaaa",
  provider: "fixture-openrouteservice",
  provider_version: "ors-api-shaped-2026-09-04",
  retrieved_at: "2026-09-04T00:00:00Z",
  licence: "ODbL 1.0",
  attribution: "openrouteservice by HeiGIT; © OpenStreetMap contributors",
  cache_status: "miss",
  constraint_results: [
    { code: "maximum_walking_distance", passed: true, actual_value: 9.13, limit_value: 10, unit: "km", message: "The round trip is within the supplied limit." },
    { code: "expedition_duration", passed: true, actual_value: 121.8, limit_value: 180, unit: "minutes", message: "Walking leaves positive field time." },
  ],
  alternative_feasible_routes: [],
  warnings: [],
  limitations: ["Historical evidence does not guarantee a sighting."],
};

export const routePlanFixture: FinalPlanView = {
  ...planFixture,
  duration_hours: 3,
  walking_plan: walkingPlanFixture,
};

export const historyFixture: HistoryView = {
  checkpoints: [
    {
      thread_id: "thread-one",
      branch_id: "branch-original",
      execution_id: "execution-original",
      checkpoint_id: "checkpoint-final",
      created_at: "2026-09-02T10:00:00Z",
      node_id: "grounding_and_safety_checks",
      graph_step: 14,
      next_nodes: [],
      terminal_status: "completed",
      applied_constraint_changes: [],
      final_checkpoint_id: "checkpoint-final",
    },
    {
      thread_id: "thread-one",
      branch_id: "branch-original",
      execution_id: "execution-original",
      checkpoint_id: "checkpoint-compose",
      created_at: "2026-09-02T09:59:00Z",
      node_id: "deterministic_validation",
      graph_step: 12,
      next_nodes: ["compose_expedition_plan"],
      applied_constraint_changes: [],
      final_checkpoint_id: "checkpoint-final",
    },
  ],
  branches: [
    {
      thread_id: "thread-one",
      branch_id: "branch-original",
      head_checkpoint_id: "checkpoint-final",
      final_checkpoint_id: "checkpoint-final",
      fork_updates: {},
      created_at: "2026-09-02T09:58:00Z",
      terminal_status: "completed",
    },
  ],
  executions: [
    {
      thread_id: "thread-one",
      execution_id: "execution-original",
      branch_id: "branch-original",
      head_checkpoint_id: "checkpoint-final",
      final_checkpoint_id: "checkpoint-final",
      created_at: "2026-09-02T09:58:00Z",
      terminal_status: "completed",
    },
  ],
};

export const workflowTopologyFixture: WorkflowTopologyView = {
  workflow_version: "phase-3.1",
  nodes: [
    { node_id: "__start__", label: "Start", stage: "entry", kind: "start", summary: "Accept an execution.", order: 0 },
    { node_id: "evidence_agent", label: "Evidence agent", stage: "evidence", kind: "model", summary: "Choose bounded evidence tools.", order: 0 },
    { node_id: "actionable_tradeoff_interrupt", label: "Actionable trade-off", stage: "validation", kind: "hitl", summary: "Pause for a human choice.", order: 0 },
    { node_id: "grounding_and_safety_checks", label: "Grounding and safety checks", stage: "planning", kind: "deterministic", summary: "Verify grounded claims.", order: 0 },
    { node_id: "__end__", label: "End", stage: "outcome", kind: "end", summary: "Persist the outcome.", order: 0 },
  ],
  edges: [
    { source: "__start__", target: "evidence_agent", conditional: false },
    { source: "evidence_agent", target: "actionable_tradeoff_interrupt", conditional: true },
    { source: "evidence_agent", target: "grounding_and_safety_checks", conditional: true },
    { source: "grounding_and_safety_checks", target: "__end__", conditional: false },
  ],
};

export const comparisonFixture: PlanComparison = {
  thread_id: "thread-one",
  checkpoint_a: "checkpoint-final",
  checkpoint_b: "checkpoint-fork",
  request_constraints: { checkpoint_a: { search_radius_km: 5 }, checkpoint_b: { search_radius_km: 8 }, changed: true },
  selected_taxon: { checkpoint_a: "Columba palumbus", checkpoint_b: "Columba palumbus", changed: false },
  evidence_outcome: { checkpoint_a: "strong_map_evidence", checkpoint_b: "strong_map_evidence", changed: false },
  weather_status: { checkpoint_a: "available", checkpoint_b: "available", changed: false },
  plan_status: { checkpoint_a: "candidate_plan_ready", checkpoint_b: "candidate_plan_ready", changed: false },
  recommended_site_ids: { checkpoint_a: ["osm-way-1"], checkpoint_b: ["osm-way-1", "osm-way-3"], changed: true },
  contextual_site_ids: { checkpoint_a: [], checkpoint_b: [], changed: false },
  limitations: { checkpoint_a: [], checkpoint_b: [], changed: false },
  provenance_sources: { checkpoint_a: ["GBIF"], checkpoint_b: ["GBIF"], changed: false },
  applied_user_decisions: { checkpoint_a: [], checkpoint_b: [{ kind: "fork_update" }], changed: true },
  route_status: { checkpoint_a: "ready", checkpoint_b: "ready", changed: false },
  selected_route_site_id: { checkpoint_a: "osm-way-1", checkpoint_b: "osm-way-3", changed: true },
  total_walking_distance_km: { checkpoint_a: 9.13, checkpoint_b: 8.7, changed: true },
  remaining_field_time_minutes: { checkpoint_a: 58.2, checkpoint_b: 64, changed: true },
  route_constraints: { checkpoint_a: [], checkpoint_b: [], changed: false },
  changed_fields: ["request_constraints", "recommended_site_ids", "applied_user_decisions"],
};

export const mapFixture: MapEvidenceView = {
  thread_id: "thread-one",
  checkpoint_id: "checkpoint-final",
  branch_id: "branch-original",
  execution_id: "execution-original",
  status: "strong",
  aggregate_grid: [],
  candidate_sites: [],
  contextual_sites: [],
  start_context: {
    type: "Feature",
    geometry: { type: "Point", coordinates: [-0.16, 51.48] },
    properties: { layer: "generalised_start", label: "Generalised SW11 start" },
  },
  selected_entrance: {
    type: "Feature",
    geometry: { type: "Point", coordinates: [-0.1519, 51.5076] },
    properties: {
      layer: "public_entrance",
      entrance_id: "osm-node-101",
      site_id: "osm-way-1",
      label: "Main gate",
      access_certainty: "explicit_public",
    },
  },
  selected_site_id: "osm-way-1",
  route_status: "ready",
  route_geometry_reference: "route-aaaaaaaaaaaaaaaaaaaaaaaa",
  attributions: ["© OpenStreetMap contributors", "GBIF.org", "Open-Meteo"],
  limitations: ["Straight-line distance is not a walking route."],
  grid_note: "Only strong-gate aggregate cells are shown.",
};

export const routeOptionsFixture: RouteOptionsView = {
  thread_id: "thread-one",
  checkpoint_id: "checkpoint-final",
  branch_id: "branch-original",
  execution_id: "execution-original",
  status: "ready",
  selected_option_id: "route-option-01",
  provider_status: "fixture-openrouteservice",
  limitations: [],
  options: [{
    option_id: "route-option-01",
    status: "ready",
    site_id: "osm-way-1",
    site_name: "Evidence Garden",
    entrance: walkingPlanFixture.entrance!,
    outbound_distance_km: 4.56,
    return_distance_km: 4.57,
    total_distance_km: 9.13,
    walking_duration_minutes: 121.8,
    feasible: true,
    provider: "fixture-openrouteservice",
    cache_status: "miss",
    route_geometry_reference: "route-aaaaaaaaaaaaaaaaaaaaaaaa",
    constraint_results: walkingPlanFixture.constraint_results,
    warnings: [],
  }],
};

export const routeGeometryFixture: RouteGeometryView = {
  thread_id: "thread-one",
  checkpoint_id: "checkpoint-final",
  route_geometry_reference: "route-aaaaaaaaaaaaaaaaaaaaaaaa",
  origin_visibility: "local_private",
  geojson: {
    type: "FeatureCollection",
    features: [
      { type: "Feature", properties: { direction: "outbound" }, geometry: { type: "LineString", coordinates: [[-0.16, 51.48], [-0.1519, 51.5076]] } },
      { type: "Feature", properties: { direction: "return" }, geometry: { type: "LineString", coordinates: [[-0.1519, 51.5076], [-0.16, 51.48]] } },
    ],
  },
  limitations: [],
};

export const stateFixture: StateView = {
  schema_version: 1,
  thread_id: "thread-one",
  branch_id: "branch-original",
  execution_id: "execution-original",
  checkpoint_id: "checkpoint-final",
  node_id: "grounding_and_safety_checks",
  graph_step: 24,
  source: "loop",
  created_at: "2026-09-02T10:00:00Z",
  next_nodes: [],
  terminal_status: "completed",
  request: { seasonal_window_radius_months: 2, search_radius_km: 6.9 },
  location: { status: "resolved", administrative_district: "Royal Borough of Greenwich" },
  taxon: { status: "resolved", accepted_taxon_key: 2478523, canonical_name: "Picus viridis" },
  evidence: { safe_map_cell_count: 4, candidate_site_count: 0, contextual_site_count: 8, public_entrance_count: 0, route_option_count: 0, tool_error_count: 1 },
  plan: { recommended_site_count: 0, contextual_site_count: 8, evidence_gate_passed: true, low_confidence_accepted: false, grounding_error_count: 0 },
  hitl: {
    waiting: false,
    applied_decisions: [
      { kind: "actionable_tradeoff", option: "widen_seasonal_window", seasonal_window_radius_months: 2, changed_fields: [] },
      { kind: "actionable_tradeoff", option: "expand_search_radius", search_radius_km: 6.9, changed_fields: [] },
    ],
  },
  counters: { evidence_loop_count: 3, plan_revision_count: 0, recorded_tool_call_count: 3 },
  invalidated_evidence: [],
};
